# configs/llava_train.yaml
model:
  model_path: /mnt/afs/share/llava_qwen2_14B-qwen35encoder-veomni-down4 
  config_path: /mnt/afs/share/llava_qwen2_14B-qwen35encoder-veomni-down4 
  model_arc: qwen2
  vision_tower: /mnt/afs/share/Qwen35_A3B_vision_encoder
  mm_downsample_ratio: 4
  image_projector_type: dynamic_avgpool
  audio_projector_type: conv_channel_upscale
  use_audio_start_end_token: true
  audio_downsample_ratio: 10


data:
  train_path: /mnt/afs/yangdeyu/GameMLLM/llava_dev/LLaVA_hub/data/stage2/train_0.jsonl
  eval_path: /mnt/afs/yangdeyu/GameMLLM/VeOmni-Dev/test_json.json
  mm_configs:
    image_max_pixels: 602112   # 768*28*28
  sample_fps: 4
  finetune_sample_frames: 64
  preprocess_workers: 2
  offset_file_path: /mnt/afs/yangdeyu/GameMLLM/VeOmni-Dev/offsets.npy
  file_maping_path: /mnt/afs/yangdeyu/GameMLLM/VeOmni-Dev/file_mapping.json

train:
  num_train_epochs: 1
  seed: 42
  local_rank: 0
  global_rank: 0
  world_size: 8

  # 模型参数
  model_max_length: 8192
  pack_seq: true
  init_device: meta

  freeze_vit: true
  freeze_vit_projector: false
  freeze_audio_tower: true
  freeze_audio_projector: true
  freeze_llm: true
  # 优化器
  optimizer:
    type: adamw
    lr: 2.0e-4
    lr_min: 2.0e-5
    weight_decay: 0.0
    max_grad_norm: 1.0
    lr_decay_style: cosine
    lr_decay_ratio: 1.0
    lr_warmup_ratio: 0.05
    lr_start: 0.0

  vit_lr: 2.0e-4
  min_lr_rate: 0.1
  enable_mixed_precision: false
  enable_batch_invariant_mode: false
  eval_steps: 0
  gc_steps: 100
  empty_cache_steps: 100
  logging_steps: 20
  gradient_checkpointing:
    enable: true
    debug: false
    enable_reentrant: false

  # FSDP / 并行
  accelerator:
    ulysses_size: 1
    enable_async: false
    fsdp_config:
      fsdp_mode: fsdp2
      full_shard: true
      reshard_after_forward: true
      reshard_after_backward: true
      offload: false
      forward_prefetch: false
    offload_config:
      enable_activation: false
      activation_gpu_limit: 0.8

  # checkpoint
  checkpoint:
    output_dir: /mnt/afs/yangdeyu/GameMLLM/VeOmni-Dev/ckpt/llava_14B
    save_steps: 100000000000
    save_total_limit: 2
    manager: dcp
    save_hf_weights: false
    save_async: true
    hf_save_steps: 20
 


  wandb:
    enable: true
    project: llavaomni
    name: llavaomni_14B_down4_8gpu_qwen35encoderr
  # dataloader
  dataloader_num_workers: 4
  dataloader_prefetch_factor: 2
  remote_dataloader: true
  broadcast_model_weights_from_rank0: true