# configs/llava_train.yaml
model:
  model_path: /hf_ckpt
  config_path: /hf_ckpt
  model_arc: qwen2
  vision_tower: /mnt/afs/share/Qwen35_A3B_vision_encoder
  mm_downsample_ratio: 16
  image_projector_type: dynamic_avgpool
  audio_projector_type: conv_channel_upscale
  use_audio_start_end_token: true
  audio_downsample_ratio: 10
  encoder_data_balance: false
  audio_max_duration: 999999
  audio_encoder_type: whisper

data:
  train_path: ""
  eval_path: /mnt/afs/yangdeyu/GameMLLM/VeOmni-Dev/exp_data/text_eval.json
  mm_configs:
    image_max_pixels: 602112   # 768*28*28
  sample_fps: 4
  finetune_sample_frames: 64
  preprocess_workers: 2
  offset_file_path: /mnt/afs/yangdeyu/GameMLLM/VeOmni-Dev/exp_data/0511_stage1_puretext/offsets.npy
  file_maping_path: /mnt/afs/yangdeyu/GameMLLM/VeOmni-Dev/exp_data/0511_stage1_puretext/file_mapping.json

train:
  num_train_epochs: 1
  seed: 42
  local_rank: 0
  global_rank: 0
  world_size: 8

  # 模型参数
  model_max_length: 8192
  pack_seq: true
  init_device: meta

  freeze_vit: true
  freeze_vit_projector: true
  freeze_audio_tower: true
  freeze_audio_projector: true
  freeze_llm: false
  output_router_logits: true
  freeze_router: false

  # 优化器
  optimizer:
    type: adamw
    lr: 1.0e-4
    lr_min: 5.0e-5
    weight_decay: 0.0
    max_grad_norm: 1.0
    lr_decay_style: cosine
    lr_decay_ratio: 1.0
    lr_warmup_ratio: 0.05
    lr_start: 0.0

  vit_lr: 1.0e-4
  min_lr_rate: 0.1
  moe_load_balance_monitor_interval: 100
  router_aux_loss_coef: 0.01
  enable_batch_invariant_mode: false
  vit_chunk_forward: false
  vit_chunk_size: 30
  eval_steps: 200
  eval_first: true
  gc_steps: 200
  empty_cache_steps: 200
  logging_steps: 50
  gradient_checkpointing:
    enable: true
    debug: false
    enable_reentrant: false

  # FSDP / 并行
  accelerator:
    ulysses_size: 1
    enable_async: false
    fsdp_config:
      fsdp_mode: fsdp2
      reshard_after_forward: true
      reshard_after_backward: true
      offload: false
      forward_prefetch: true
      mixed_precision:
        enable: true
    offload_config:
      enable_activation: false
      activation_gpu_limit: 0.8

  # checkpoint
  checkpoint:
    output_dir: /ckpt/llavaomni_30A3B_qwen35encoder_puretext_lr1e4
    save_steps: 1000
    save_epochs: 1
    save_total_limit: 2
    manager: dcp
    save_hf_weights: true
    save_async: true
    hf_save_steps: 0 # only save at epoch end
 
  wandb:
    enable: true
    project: llavaomni
    name: llavaomni_30A3B_qwen35encoder_puretext_lr1e4
  # dataloader
  dataloader_num_workers: 4
  dataloader_prefetch_factor: 2
  remote_dataloader: true
  broadcast_model_weights_from_rank0: true